/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef TMapPhoneNumberPubkeyKVService_H
#define TMapPhoneNumberPubkeyKVService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "i2skv_types.h"
#include "TDataService.h"

namespace OpenStars { namespace Common { namespace MapPhoneNumberPubkeyKV {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class TMapPhoneNumberPubkeyKVServiceIf : virtual public TDataServiceIf {
 public:
  virtual ~TMapPhoneNumberPubkeyKVServiceIf() {}
};

class TMapPhoneNumberPubkeyKVServiceIfFactory : virtual public TDataServiceIfFactory {
 public:
  typedef TMapPhoneNumberPubkeyKVServiceIf Handler;

  virtual ~TMapPhoneNumberPubkeyKVServiceIfFactory() {}

  virtual TMapPhoneNumberPubkeyKVServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(TDataServiceIf* /* handler */) = 0;
};

class TMapPhoneNumberPubkeyKVServiceIfSingletonFactory : virtual public TMapPhoneNumberPubkeyKVServiceIfFactory {
 public:
  TMapPhoneNumberPubkeyKVServiceIfSingletonFactory(const ::apache::thrift::stdcxx::shared_ptr<TMapPhoneNumberPubkeyKVServiceIf>& iface) : iface_(iface) {}
  virtual ~TMapPhoneNumberPubkeyKVServiceIfSingletonFactory() {}

  virtual TMapPhoneNumberPubkeyKVServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(TDataServiceIf* /* handler */) {}

 protected:
  ::apache::thrift::stdcxx::shared_ptr<TMapPhoneNumberPubkeyKVServiceIf> iface_;
};

class TMapPhoneNumberPubkeyKVServiceNull : virtual public TMapPhoneNumberPubkeyKVServiceIf , virtual public TDataServiceNull {
 public:
  virtual ~TMapPhoneNumberPubkeyKVServiceNull() {}
};

class TMapPhoneNumberPubkeyKVServiceClient : virtual public TMapPhoneNumberPubkeyKVServiceIf, public TDataServiceClient {
 public:
  TMapPhoneNumberPubkeyKVServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    TDataServiceClient(prot, prot) {}
  TMapPhoneNumberPubkeyKVServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :    TDataServiceClient(iprot, oprot) {}
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
};

class TMapPhoneNumberPubkeyKVServiceProcessor : public TDataServiceProcessor {
 protected:
  ::apache::thrift::stdcxx::shared_ptr<TMapPhoneNumberPubkeyKVServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (TMapPhoneNumberPubkeyKVServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
 public:
  TMapPhoneNumberPubkeyKVServiceProcessor(::apache::thrift::stdcxx::shared_ptr<TMapPhoneNumberPubkeyKVServiceIf> iface) :
    TDataServiceProcessor(iface),
    iface_(iface) {
  }

  virtual ~TMapPhoneNumberPubkeyKVServiceProcessor() {}
};

class TMapPhoneNumberPubkeyKVServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  TMapPhoneNumberPubkeyKVServiceProcessorFactory(const ::apache::thrift::stdcxx::shared_ptr< TMapPhoneNumberPubkeyKVServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::apache::thrift::stdcxx::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::apache::thrift::stdcxx::shared_ptr< TMapPhoneNumberPubkeyKVServiceIfFactory > handlerFactory_;
};

class TMapPhoneNumberPubkeyKVServiceMultiface : virtual public TMapPhoneNumberPubkeyKVServiceIf, public TDataServiceMultiface {
 public:
  TMapPhoneNumberPubkeyKVServiceMultiface(std::vector<apache::thrift::stdcxx::shared_ptr<TMapPhoneNumberPubkeyKVServiceIf> >& ifaces) : ifaces_(ifaces) {
    std::vector<apache::thrift::stdcxx::shared_ptr<TMapPhoneNumberPubkeyKVServiceIf> >::iterator iter;
    for (iter = ifaces.begin(); iter != ifaces.end(); ++iter) {
      TDataServiceMultiface::add(*iter);
    }
  }
  virtual ~TMapPhoneNumberPubkeyKVServiceMultiface() {}
 protected:
  std::vector<apache::thrift::stdcxx::shared_ptr<TMapPhoneNumberPubkeyKVServiceIf> > ifaces_;
  TMapPhoneNumberPubkeyKVServiceMultiface() {}
  void add(::apache::thrift::stdcxx::shared_ptr<TMapPhoneNumberPubkeyKVServiceIf> iface) {
    TDataServiceMultiface::add(iface);
    ifaces_.push_back(iface);
  }
 public:
};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class TMapPhoneNumberPubkeyKVServiceConcurrentClient : virtual public TMapPhoneNumberPubkeyKVServiceIf, public TDataServiceConcurrentClient {
 public:
  TMapPhoneNumberPubkeyKVServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    TDataServiceConcurrentClient(prot, prot) {}
  TMapPhoneNumberPubkeyKVServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :    TDataServiceConcurrentClient(iprot, oprot) {}
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

}}} // namespace

#endif
