// Autogenerated by Thrift Compiler (0.13.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
	"context"
	"flag"
	"fmt"
	"math"
	"net"
	"net/url"
	"os"
	"strconv"
	"strings"
	"github.com/apache/thrift/lib/go/thrift"
	"openstars/core/bigset/listi64"
)

var _ = listi64.GoUnusedProtection__

func Usage() {
  fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
  flag.PrintDefaults()
  fmt.Fprintln(os.Stderr, "\nFunctions:")
  fmt.Fprintln(os.Stderr, "  TPutItemResult putItem(TKey bigsetID, TItem item)")
  fmt.Fprintln(os.Stderr, "  TChildItemResult addChildItem(TKey bsName, TItemKey itemKey, TItemChild aChild, TChildItemOptions opOption)")
  fmt.Fprintln(os.Stderr, "  TChildItemResult addChildrenItem(TKey bsName, TItemKey itemKey,  aChild, TChildItemOptions opOption)")
  fmt.Fprintln(os.Stderr, "  TChildItemResult removeChildItem(TKey bsName, TItemKey itemKey, TItemChild aChild, TChildItemOptions opOption)")
  fmt.Fprintln(os.Stderr, "  bool removeItem(TKey bigsetID, TItemKey itemKey)")
  fmt.Fprintln(os.Stderr, "  TExistedResult existed(TKey bigsetID, TItemKey itemKey)")
  fmt.Fprintln(os.Stderr, "  TItemResult getItem(TKey bigsetID, TItemKey itemKey)")
  fmt.Fprintln(os.Stderr, "  TItemSetResult getSlice(TKey bigsetID, i32 fromIDX, i32 count)")
  fmt.Fprintln(os.Stderr, "  TItemSetResult getSliceFromItem(TKey bigsetID, TItemKey fromKey, i32 count)")
  fmt.Fprintln(os.Stderr, "  TItemSetResult getSliceR(TKey bigsetID, i32 fromIDX, i32 count)")
  fmt.Fprintln(os.Stderr, "  TItemSetResult getSliceFromItemR(TKey bigsetID, TItemKey fromKey, i32 count)")
  fmt.Fprintln(os.Stderr, "  TItemSetResult rangeQuery(TKey bigsetID, TItemKey startKey, TItemKey endKey)")
  fmt.Fprintln(os.Stderr, "  bool bulkLoad(TKey bigsetID, TItemSet setData)")
  fmt.Fprintln(os.Stderr, "  TMultiPutItemResult multiPut(TKey bigsetID, TItemSet setData, bool getAddedItems, bool getReplacedItems)")
  fmt.Fprintln(os.Stderr, "  i64 getTotalCount(TKey bigsetID)")
  fmt.Fprintln(os.Stderr, "  i64 removeAll(TKey bigsetID)")
  fmt.Fprintln(os.Stderr)
  os.Exit(0)
}

type httpHeaders map[string]string

func (h httpHeaders) String() string {
  var m map[string]string = h
  return fmt.Sprintf("%s", m)
}

func (h httpHeaders) Set(value string) error {
  parts := strings.Split(value, ": ")
  if len(parts) != 2 {
    return fmt.Errorf("header should be of format 'Key: Value'")
  }
  h[parts[0]] = parts[1]
  return nil
}

func main() {
  flag.Usage = Usage
  var host string
  var port int
  var protocol string
  var urlString string
  var framed bool
  var useHttp bool
  headers := make(httpHeaders)
  var parsedUrl *url.URL
  var trans thrift.TTransport
  _ = strconv.Atoi
  _ = math.Abs
  flag.Usage = Usage
  flag.StringVar(&host, "h", "localhost", "Specify host and port")
  flag.IntVar(&port, "p", 9090, "Specify port")
  flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
  flag.StringVar(&urlString, "u", "", "Specify the url")
  flag.BoolVar(&framed, "framed", false, "Use framed transport")
  flag.BoolVar(&useHttp, "http", false, "Use http")
  flag.Var(headers, "H", "Headers to set on the http(s) request (e.g. -H \"Key: Value\")")
  flag.Parse()
  
  if len(urlString) > 0 {
    var err error
    parsedUrl, err = url.Parse(urlString)
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
    host = parsedUrl.Host
    useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http" || parsedUrl.Scheme == "https"
  } else if useHttp {
    _, err := url.Parse(fmt.Sprint("http://", host, ":", port))
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
  }
  
  cmd := flag.Arg(0)
  var err error
  if useHttp {
    trans, err = thrift.NewTHttpClient(parsedUrl.String())
    if len(headers) > 0 {
      httptrans := trans.(*thrift.THttpClient)
      for key, value := range headers {
        httptrans.SetHeader(key, value)
      }
    }
  } else {
    portStr := fmt.Sprint(port)
    if strings.Contains(host, ":") {
           host, portStr, err = net.SplitHostPort(host)
           if err != nil {
                   fmt.Fprintln(os.Stderr, "error with host:", err)
                   os.Exit(1)
           }
    }
    trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
    if err != nil {
      fmt.Fprintln(os.Stderr, "error resolving address:", err)
      os.Exit(1)
    }
    if framed {
      trans = thrift.NewTFramedTransport(trans)
    }
  }
  if err != nil {
    fmt.Fprintln(os.Stderr, "Error creating transport", err)
    os.Exit(1)
  }
  defer trans.Close()
  var protocolFactory thrift.TProtocolFactory
  switch protocol {
  case "compact":
    protocolFactory = thrift.NewTCompactProtocolFactory()
    break
  case "simplejson":
    protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
    break
  case "json":
    protocolFactory = thrift.NewTJSONProtocolFactory()
    break
  case "binary", "":
    protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
    Usage()
    os.Exit(1)
  }
  iprot := protocolFactory.GetProtocol(trans)
  oprot := protocolFactory.GetProtocol(trans)
  client := listi64.NewTIBSListI64ServiceClient(thrift.NewTStandardClient(iprot, oprot))
  if err := trans.Open(); err != nil {
    fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
    os.Exit(1)
  }
  
  switch cmd {
  case "putItem":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "PutItem requires 2 args")
      flag.Usage()
    }
    argvalue0, err260 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err260 != nil {
      Usage()
      return
    }
    value0 := listi64.TKey(argvalue0)
    arg261 := flag.Arg(2)
    mbTrans262 := thrift.NewTMemoryBufferLen(len(arg261))
    defer mbTrans262.Close()
    _, err263 := mbTrans262.WriteString(arg261)
    if err263 != nil {
      Usage()
      return
    }
    factory264 := thrift.NewTJSONProtocolFactory()
    jsProt265 := factory264.GetProtocol(mbTrans262)
    argvalue1 := listi64.NewTItem()
    err266 := argvalue1.Read(jsProt265)
    if err266 != nil {
      Usage()
      return
    }
    value1 := argvalue1
    fmt.Print(client.PutItem(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "addChildItem":
    if flag.NArg() - 1 != 4 {
      fmt.Fprintln(os.Stderr, "AddChildItem requires 4 args")
      flag.Usage()
    }
    argvalue0, err267 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err267 != nil {
      Usage()
      return
    }
    value0 := listi64.TKey(argvalue0)
    argvalue1 := []byte(flag.Arg(2))
    value1 := listi64.TItemKey(argvalue1)
    argvalue2, err269 := (strconv.ParseInt(flag.Arg(3), 10, 64))
    if err269 != nil {
      Usage()
      return
    }
    value2 := listi64.TItemChild(argvalue2)
    tmp3, err := (strconv.Atoi(flag.Arg(4)))
    if err != nil {
      Usage()
     return
    }
    argvalue3 := listi64.TChildItemOptions(tmp3)
    value3 := argvalue3
    fmt.Print(client.AddChildItem(context.Background(), value0, value1, value2, value3))
    fmt.Print("\n")
    break
  case "addChildrenItem":
    if flag.NArg() - 1 != 4 {
      fmt.Fprintln(os.Stderr, "AddChildrenItem requires 4 args")
      flag.Usage()
    }
    argvalue0, err270 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err270 != nil {
      Usage()
      return
    }
    value0 := listi64.TKey(argvalue0)
    argvalue1 := []byte(flag.Arg(2))
    value1 := listi64.TItemKey(argvalue1)
    arg272 := flag.Arg(3)
    mbTrans273 := thrift.NewTMemoryBufferLen(len(arg272))
    defer mbTrans273.Close()
    _, err274 := mbTrans273.WriteString(arg272)
    if err274 != nil { 
      Usage()
      return
    }
    factory275 := thrift.NewTJSONProtocolFactory()
    jsProt276 := factory275.GetProtocol(mbTrans273)
    containerStruct2 := listi64.NewTIBSListI64ServiceAddChildrenItemArgs()
    err277 := containerStruct2.ReadField3(jsProt276)
    if err277 != nil {
      Usage()
      return
    }
    argvalue2 := containerStruct2.AChild
    value2 := argvalue2
    tmp3, err := (strconv.Atoi(flag.Arg(4)))
    if err != nil {
      Usage()
     return
    }
    argvalue3 := listi64.TChildItemOptions(tmp3)
    value3 := argvalue3
    fmt.Print(client.AddChildrenItem(context.Background(), value0, value1, value2, value3))
    fmt.Print("\n")
    break
  case "removeChildItem":
    if flag.NArg() - 1 != 4 {
      fmt.Fprintln(os.Stderr, "RemoveChildItem requires 4 args")
      flag.Usage()
    }
    argvalue0, err278 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err278 != nil {
      Usage()
      return
    }
    value0 := listi64.TKey(argvalue0)
    argvalue1 := []byte(flag.Arg(2))
    value1 := listi64.TItemKey(argvalue1)
    argvalue2, err280 := (strconv.ParseInt(flag.Arg(3), 10, 64))
    if err280 != nil {
      Usage()
      return
    }
    value2 := listi64.TItemChild(argvalue2)
    tmp3, err := (strconv.Atoi(flag.Arg(4)))
    if err != nil {
      Usage()
     return
    }
    argvalue3 := listi64.TChildItemOptions(tmp3)
    value3 := argvalue3
    fmt.Print(client.RemoveChildItem(context.Background(), value0, value1, value2, value3))
    fmt.Print("\n")
    break
  case "removeItem":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "RemoveItem requires 2 args")
      flag.Usage()
    }
    argvalue0, err281 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err281 != nil {
      Usage()
      return
    }
    value0 := listi64.TKey(argvalue0)
    argvalue1 := []byte(flag.Arg(2))
    value1 := listi64.TItemKey(argvalue1)
    fmt.Print(client.RemoveItem(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "existed":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "Existed requires 2 args")
      flag.Usage()
    }
    argvalue0, err283 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err283 != nil {
      Usage()
      return
    }
    value0 := listi64.TKey(argvalue0)
    argvalue1 := []byte(flag.Arg(2))
    value1 := listi64.TItemKey(argvalue1)
    fmt.Print(client.Existed(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "getItem":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "GetItem requires 2 args")
      flag.Usage()
    }
    argvalue0, err285 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err285 != nil {
      Usage()
      return
    }
    value0 := listi64.TKey(argvalue0)
    argvalue1 := []byte(flag.Arg(2))
    value1 := listi64.TItemKey(argvalue1)
    fmt.Print(client.GetItem(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "getSlice":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "GetSlice requires 3 args")
      flag.Usage()
    }
    argvalue0, err287 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err287 != nil {
      Usage()
      return
    }
    value0 := listi64.TKey(argvalue0)
    tmp1, err288 := (strconv.Atoi(flag.Arg(2)))
    if err288 != nil {
      Usage()
      return
    }
    argvalue1 := int32(tmp1)
    value1 := argvalue1
    tmp2, err289 := (strconv.Atoi(flag.Arg(3)))
    if err289 != nil {
      Usage()
      return
    }
    argvalue2 := int32(tmp2)
    value2 := argvalue2
    fmt.Print(client.GetSlice(context.Background(), value0, value1, value2))
    fmt.Print("\n")
    break
  case "getSliceFromItem":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "GetSliceFromItem requires 3 args")
      flag.Usage()
    }
    argvalue0, err290 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err290 != nil {
      Usage()
      return
    }
    value0 := listi64.TKey(argvalue0)
    argvalue1 := []byte(flag.Arg(2))
    value1 := listi64.TItemKey(argvalue1)
    tmp2, err292 := (strconv.Atoi(flag.Arg(3)))
    if err292 != nil {
      Usage()
      return
    }
    argvalue2 := int32(tmp2)
    value2 := argvalue2
    fmt.Print(client.GetSliceFromItem(context.Background(), value0, value1, value2))
    fmt.Print("\n")
    break
  case "getSliceR":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "GetSliceR requires 3 args")
      flag.Usage()
    }
    argvalue0, err293 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err293 != nil {
      Usage()
      return
    }
    value0 := listi64.TKey(argvalue0)
    tmp1, err294 := (strconv.Atoi(flag.Arg(2)))
    if err294 != nil {
      Usage()
      return
    }
    argvalue1 := int32(tmp1)
    value1 := argvalue1
    tmp2, err295 := (strconv.Atoi(flag.Arg(3)))
    if err295 != nil {
      Usage()
      return
    }
    argvalue2 := int32(tmp2)
    value2 := argvalue2
    fmt.Print(client.GetSliceR(context.Background(), value0, value1, value2))
    fmt.Print("\n")
    break
  case "getSliceFromItemR":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "GetSliceFromItemR requires 3 args")
      flag.Usage()
    }
    argvalue0, err296 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err296 != nil {
      Usage()
      return
    }
    value0 := listi64.TKey(argvalue0)
    argvalue1 := []byte(flag.Arg(2))
    value1 := listi64.TItemKey(argvalue1)
    tmp2, err298 := (strconv.Atoi(flag.Arg(3)))
    if err298 != nil {
      Usage()
      return
    }
    argvalue2 := int32(tmp2)
    value2 := argvalue2
    fmt.Print(client.GetSliceFromItemR(context.Background(), value0, value1, value2))
    fmt.Print("\n")
    break
  case "rangeQuery":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "RangeQuery requires 3 args")
      flag.Usage()
    }
    argvalue0, err299 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err299 != nil {
      Usage()
      return
    }
    value0 := listi64.TKey(argvalue0)
    argvalue1 := []byte(flag.Arg(2))
    value1 := listi64.TItemKey(argvalue1)
    argvalue2 := []byte(flag.Arg(3))
    value2 := listi64.TItemKey(argvalue2)
    fmt.Print(client.RangeQuery(context.Background(), value0, value1, value2))
    fmt.Print("\n")
    break
  case "bulkLoad":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "BulkLoad requires 2 args")
      flag.Usage()
    }
    argvalue0, err302 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err302 != nil {
      Usage()
      return
    }
    value0 := listi64.TKey(argvalue0)
    arg303 := flag.Arg(2)
    mbTrans304 := thrift.NewTMemoryBufferLen(len(arg303))
    defer mbTrans304.Close()
    _, err305 := mbTrans304.WriteString(arg303)
    if err305 != nil {
      Usage()
      return
    }
    factory306 := thrift.NewTJSONProtocolFactory()
    jsProt307 := factory306.GetProtocol(mbTrans304)
    argvalue1 := listi64.NewTItemSet()
    err308 := argvalue1.Read(jsProt307)
    if err308 != nil {
      Usage()
      return
    }
    value1 := argvalue1
    fmt.Print(client.BulkLoad(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "multiPut":
    if flag.NArg() - 1 != 4 {
      fmt.Fprintln(os.Stderr, "MultiPut requires 4 args")
      flag.Usage()
    }
    argvalue0, err309 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err309 != nil {
      Usage()
      return
    }
    value0 := listi64.TKey(argvalue0)
    arg310 := flag.Arg(2)
    mbTrans311 := thrift.NewTMemoryBufferLen(len(arg310))
    defer mbTrans311.Close()
    _, err312 := mbTrans311.WriteString(arg310)
    if err312 != nil {
      Usage()
      return
    }
    factory313 := thrift.NewTJSONProtocolFactory()
    jsProt314 := factory313.GetProtocol(mbTrans311)
    argvalue1 := listi64.NewTItemSet()
    err315 := argvalue1.Read(jsProt314)
    if err315 != nil {
      Usage()
      return
    }
    value1 := argvalue1
    argvalue2 := flag.Arg(3) == "true"
    value2 := argvalue2
    argvalue3 := flag.Arg(4) == "true"
    value3 := argvalue3
    fmt.Print(client.MultiPut(context.Background(), value0, value1, value2, value3))
    fmt.Print("\n")
    break
  case "getTotalCount":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetTotalCount requires 1 args")
      flag.Usage()
    }
    argvalue0, err318 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err318 != nil {
      Usage()
      return
    }
    value0 := listi64.TKey(argvalue0)
    fmt.Print(client.GetTotalCount(context.Background(), value0))
    fmt.Print("\n")
    break
  case "removeAll":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "RemoveAll requires 1 args")
      flag.Usage()
    }
    argvalue0, err319 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err319 != nil {
      Usage()
      return
    }
    value0 := listi64.TKey(argvalue0)
    fmt.Print(client.RemoveAll(context.Background(), value0))
    fmt.Print("\n")
    break
  case "":
    Usage()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
  }
}
