/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "i2skv_constants.h"

namespace OpenStars { namespace Common { namespace MapPhoneNumberPubkeyKV {

const i2skvConstants g_i2skv_constants;

i2skvConstants::i2skvConstants() {
}

}}} // namespace

