/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef i2skv_CONSTANTS_H
#define i2skv_CONSTANTS_H

#include "i2skv_types.h"

namespace OpenStars { namespace Common { namespace MapPhoneNumberPubkeyKV {

class i2skvConstants {
 public:
  i2skvConstants();

};

extern const i2skvConstants g_i2skv_constants;

}}} // namespace

#endif
