/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef TDataService_H
#define TDataService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "i2skv_types.h"

namespace OpenStars { namespace Common { namespace MapPhoneNumberPubkeyKV {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class TDataServiceIf {
 public:
  virtual ~TDataServiceIf() {}
  virtual void getTokenByPubkey(TDataResult& _return, const std::string& pubkey) = 0;
  virtual void getPubkeyByToken(TDataResult& _return, const std::string& token) = 0;
  virtual TErrorCode::type putData(const std::string& pubkey, const std::string& token) = 0;
};

class TDataServiceIfFactory {
 public:
  typedef TDataServiceIf Handler;

  virtual ~TDataServiceIfFactory() {}

  virtual TDataServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(TDataServiceIf* /* handler */) = 0;
};

class TDataServiceIfSingletonFactory : virtual public TDataServiceIfFactory {
 public:
  TDataServiceIfSingletonFactory(const ::apache::thrift::stdcxx::shared_ptr<TDataServiceIf>& iface) : iface_(iface) {}
  virtual ~TDataServiceIfSingletonFactory() {}

  virtual TDataServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(TDataServiceIf* /* handler */) {}

 protected:
  ::apache::thrift::stdcxx::shared_ptr<TDataServiceIf> iface_;
};

class TDataServiceNull : virtual public TDataServiceIf {
 public:
  virtual ~TDataServiceNull() {}
  void getTokenByPubkey(TDataResult& /* _return */, const std::string& /* pubkey */) {
    return;
  }
  void getPubkeyByToken(TDataResult& /* _return */, const std::string& /* token */) {
    return;
  }
  TErrorCode::type putData(const std::string& /* pubkey */, const std::string& /* token */) {
    TErrorCode::type _return = (TErrorCode::type)0;
    return _return;
  }
};

typedef struct _TDataService_getTokenByPubkey_args__isset {
  _TDataService_getTokenByPubkey_args__isset() : pubkey(false) {}
  bool pubkey :1;
} _TDataService_getTokenByPubkey_args__isset;

class TDataService_getTokenByPubkey_args {
 public:

  TDataService_getTokenByPubkey_args(const TDataService_getTokenByPubkey_args&);
  TDataService_getTokenByPubkey_args& operator=(const TDataService_getTokenByPubkey_args&);
  TDataService_getTokenByPubkey_args() : pubkey() {
  }

  virtual ~TDataService_getTokenByPubkey_args() throw();
  std::string pubkey;

  _TDataService_getTokenByPubkey_args__isset __isset;

  void __set_pubkey(const std::string& val);

  bool operator == (const TDataService_getTokenByPubkey_args & rhs) const
  {
    if (!(pubkey == rhs.pubkey))
      return false;
    return true;
  }
  bool operator != (const TDataService_getTokenByPubkey_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TDataService_getTokenByPubkey_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class TDataService_getTokenByPubkey_pargs {
 public:


  virtual ~TDataService_getTokenByPubkey_pargs() throw();
  const std::string* pubkey;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TDataService_getTokenByPubkey_result__isset {
  _TDataService_getTokenByPubkey_result__isset() : success(false) {}
  bool success :1;
} _TDataService_getTokenByPubkey_result__isset;

class TDataService_getTokenByPubkey_result {
 public:

  TDataService_getTokenByPubkey_result(const TDataService_getTokenByPubkey_result&);
  TDataService_getTokenByPubkey_result& operator=(const TDataService_getTokenByPubkey_result&);
  TDataService_getTokenByPubkey_result() {
  }

  virtual ~TDataService_getTokenByPubkey_result() throw();
  TDataResult success;

  _TDataService_getTokenByPubkey_result__isset __isset;

  void __set_success(const TDataResult& val);

  bool operator == (const TDataService_getTokenByPubkey_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const TDataService_getTokenByPubkey_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TDataService_getTokenByPubkey_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TDataService_getTokenByPubkey_presult__isset {
  _TDataService_getTokenByPubkey_presult__isset() : success(false) {}
  bool success :1;
} _TDataService_getTokenByPubkey_presult__isset;

class TDataService_getTokenByPubkey_presult {
 public:


  virtual ~TDataService_getTokenByPubkey_presult() throw();
  TDataResult* success;

  _TDataService_getTokenByPubkey_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _TDataService_getPubkeyByToken_args__isset {
  _TDataService_getPubkeyByToken_args__isset() : token(false) {}
  bool token :1;
} _TDataService_getPubkeyByToken_args__isset;

class TDataService_getPubkeyByToken_args {
 public:

  TDataService_getPubkeyByToken_args(const TDataService_getPubkeyByToken_args&);
  TDataService_getPubkeyByToken_args& operator=(const TDataService_getPubkeyByToken_args&);
  TDataService_getPubkeyByToken_args() : token() {
  }

  virtual ~TDataService_getPubkeyByToken_args() throw();
  std::string token;

  _TDataService_getPubkeyByToken_args__isset __isset;

  void __set_token(const std::string& val);

  bool operator == (const TDataService_getPubkeyByToken_args & rhs) const
  {
    if (!(token == rhs.token))
      return false;
    return true;
  }
  bool operator != (const TDataService_getPubkeyByToken_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TDataService_getPubkeyByToken_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class TDataService_getPubkeyByToken_pargs {
 public:


  virtual ~TDataService_getPubkeyByToken_pargs() throw();
  const std::string* token;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TDataService_getPubkeyByToken_result__isset {
  _TDataService_getPubkeyByToken_result__isset() : success(false) {}
  bool success :1;
} _TDataService_getPubkeyByToken_result__isset;

class TDataService_getPubkeyByToken_result {
 public:

  TDataService_getPubkeyByToken_result(const TDataService_getPubkeyByToken_result&);
  TDataService_getPubkeyByToken_result& operator=(const TDataService_getPubkeyByToken_result&);
  TDataService_getPubkeyByToken_result() {
  }

  virtual ~TDataService_getPubkeyByToken_result() throw();
  TDataResult success;

  _TDataService_getPubkeyByToken_result__isset __isset;

  void __set_success(const TDataResult& val);

  bool operator == (const TDataService_getPubkeyByToken_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const TDataService_getPubkeyByToken_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TDataService_getPubkeyByToken_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TDataService_getPubkeyByToken_presult__isset {
  _TDataService_getPubkeyByToken_presult__isset() : success(false) {}
  bool success :1;
} _TDataService_getPubkeyByToken_presult__isset;

class TDataService_getPubkeyByToken_presult {
 public:


  virtual ~TDataService_getPubkeyByToken_presult() throw();
  TDataResult* success;

  _TDataService_getPubkeyByToken_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _TDataService_putData_args__isset {
  _TDataService_putData_args__isset() : pubkey(false), token(false) {}
  bool pubkey :1;
  bool token :1;
} _TDataService_putData_args__isset;

class TDataService_putData_args {
 public:

  TDataService_putData_args(const TDataService_putData_args&);
  TDataService_putData_args& operator=(const TDataService_putData_args&);
  TDataService_putData_args() : pubkey(), token() {
  }

  virtual ~TDataService_putData_args() throw();
  std::string pubkey;
  std::string token;

  _TDataService_putData_args__isset __isset;

  void __set_pubkey(const std::string& val);

  void __set_token(const std::string& val);

  bool operator == (const TDataService_putData_args & rhs) const
  {
    if (!(pubkey == rhs.pubkey))
      return false;
    if (!(token == rhs.token))
      return false;
    return true;
  }
  bool operator != (const TDataService_putData_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TDataService_putData_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class TDataService_putData_pargs {
 public:


  virtual ~TDataService_putData_pargs() throw();
  const std::string* pubkey;
  const std::string* token;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TDataService_putData_result__isset {
  _TDataService_putData_result__isset() : success(false) {}
  bool success :1;
} _TDataService_putData_result__isset;

class TDataService_putData_result {
 public:

  TDataService_putData_result(const TDataService_putData_result&);
  TDataService_putData_result& operator=(const TDataService_putData_result&);
  TDataService_putData_result() : success((TErrorCode::type)0) {
  }

  virtual ~TDataService_putData_result() throw();
  TErrorCode::type success;

  _TDataService_putData_result__isset __isset;

  void __set_success(const TErrorCode::type val);

  bool operator == (const TDataService_putData_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const TDataService_putData_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TDataService_putData_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TDataService_putData_presult__isset {
  _TDataService_putData_presult__isset() : success(false) {}
  bool success :1;
} _TDataService_putData_presult__isset;

class TDataService_putData_presult {
 public:


  virtual ~TDataService_putData_presult() throw();
  TErrorCode::type* success;

  _TDataService_putData_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class TDataServiceClient : virtual public TDataServiceIf {
 public:
  TDataServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  TDataServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void getTokenByPubkey(TDataResult& _return, const std::string& pubkey);
  void send_getTokenByPubkey(const std::string& pubkey);
  void recv_getTokenByPubkey(TDataResult& _return);
  void getPubkeyByToken(TDataResult& _return, const std::string& token);
  void send_getPubkeyByToken(const std::string& token);
  void recv_getPubkeyByToken(TDataResult& _return);
  TErrorCode::type putData(const std::string& pubkey, const std::string& token);
  void send_putData(const std::string& pubkey, const std::string& token);
  TErrorCode::type recv_putData();
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class TDataServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::apache::thrift::stdcxx::shared_ptr<TDataServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (TDataServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_getTokenByPubkey(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getPubkeyByToken(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_putData(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  TDataServiceProcessor(::apache::thrift::stdcxx::shared_ptr<TDataServiceIf> iface) :
    iface_(iface) {
    processMap_["getTokenByPubkey"] = &TDataServiceProcessor::process_getTokenByPubkey;
    processMap_["getPubkeyByToken"] = &TDataServiceProcessor::process_getPubkeyByToken;
    processMap_["putData"] = &TDataServiceProcessor::process_putData;
  }

  virtual ~TDataServiceProcessor() {}
};

class TDataServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  TDataServiceProcessorFactory(const ::apache::thrift::stdcxx::shared_ptr< TDataServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::apache::thrift::stdcxx::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::apache::thrift::stdcxx::shared_ptr< TDataServiceIfFactory > handlerFactory_;
};

class TDataServiceMultiface : virtual public TDataServiceIf {
 public:
  TDataServiceMultiface(std::vector<apache::thrift::stdcxx::shared_ptr<TDataServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~TDataServiceMultiface() {}
 protected:
  std::vector<apache::thrift::stdcxx::shared_ptr<TDataServiceIf> > ifaces_;
  TDataServiceMultiface() {}
  void add(::apache::thrift::stdcxx::shared_ptr<TDataServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void getTokenByPubkey(TDataResult& _return, const std::string& pubkey) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getTokenByPubkey(_return, pubkey);
    }
    ifaces_[i]->getTokenByPubkey(_return, pubkey);
    return;
  }

  void getPubkeyByToken(TDataResult& _return, const std::string& token) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getPubkeyByToken(_return, token);
    }
    ifaces_[i]->getPubkeyByToken(_return, token);
    return;
  }

  TErrorCode::type putData(const std::string& pubkey, const std::string& token) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->putData(pubkey, token);
    }
    return ifaces_[i]->putData(pubkey, token);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class TDataServiceConcurrentClient : virtual public TDataServiceIf {
 public:
  TDataServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  TDataServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void getTokenByPubkey(TDataResult& _return, const std::string& pubkey);
  int32_t send_getTokenByPubkey(const std::string& pubkey);
  void recv_getTokenByPubkey(TDataResult& _return, const int32_t seqid);
  void getPubkeyByToken(TDataResult& _return, const std::string& token);
  int32_t send_getPubkeyByToken(const std::string& token);
  void recv_getPubkeyByToken(TDataResult& _return, const int32_t seqid);
  TErrorCode::type putData(const std::string& pubkey, const std::string& token);
  int32_t send_putData(const std::string& pubkey, const std::string& token);
  TErrorCode::type recv_putData(const int32_t seqid);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

}}} // namespace

#endif
